name: "Deploy a stack to Portainer updated"
description: "Github Action to deploy a stack to a Portainer instance"
author: "SCOD <scod-br>"
branding:
  icon: "upload-cloud"
  color: "orange"

inputs:
  portainer-host:
    required: true
    description: "Portainer host, eg. https://myportainer.instance.com"
  username:
    required: true
    description: "Username for the Portainer login. NOTE: Do not use admin account! Create a new CI specific login"
  password:
    required: true
    description: "Password for the Portainer login"
  swarm-id:
    required: false
    description: "ID of the swarm. Only required if you deploy to a swarm."
  endpoint-id:
    required: false
    description: "ID of the Portainer node to deploy to"
  stack-name:
    required: true
    description: "Name for the Portainer stack"
  stack-definition:
    required: false
    description: "The path to the docker-compose stack stack definition file, eg. stack-definition.yml"
  template-variables:
    required: false
    description: "If given, these variables will be replaced in docker-compose file by handlebars"
  env-variables:
    required: false
    description: "Environment variables to set in the stack, eg. VARIABLE1=value1\nVARIABLE2=value2"
  image:
    required: false
    description: "The URI of the container image to insert into the stack definition, eg. docker.pkg.github.com/username/repo/master"
  prune-stack:
    required: false
    description: "If true, the stack will be pruned before deployment"
  pull-image:
    required: false
    description: "If true, the image will be pulled before deployment"

runs:
  using: "node20"
  main: "dist/index.js"
